---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cobalt
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cobalt
  template:
    metadata:
      labels:
        app: cobalt
    spec:
      containers:
      - name: cobalt
        image: ghcr.io/imputnet/cobalt:11
        ports:
        - containerPort: 31000
        env:
        - name: API_URL
          value: "http://cobalt.default.svc.cluster.local:31000"
        - name: API_PORT
          value: "31000"

---
apiVersion: v1
kind: Service
metadata:
  name: cobalt
  namespace: default
spec:
  type: NodePort
  selector:
    app: cobalt
  ports:
    - port: 31000
      targetPort: 31000
      nodePort: 31000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediadownloadbot
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediadownloadbot
  template:
    metadata:
      labels:
        app: mediadownloadbot
    spec:
      containers:
      - name: mediadownloadbot
        image: ghcr.io/netherquartz/mediadownloadbot:latest
        env:
        - name: COBALT_URL
          value: "http://cobalt.default.svc.cluster.local:31000"  # requires Cobalt>=11
        - name: LOGGING_LEVEL
          value: "DEBUG"
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: mediadownloadbot-secret
              key: TOKEN
