services:
  mediadownloadbot:
    build: .
    image: mediadownbot:latest
    container_name: mediadownloadbot
    restart: always
    environment:
      - TOKEN
      - LOGGING_LEVEL
      - COBALT_URL
    mem_limit: 400m
