services:
  mediadownloadbot:
    build: .
    image: ghcr.io/netherquartz/mediadownloadbot:latest
    container_name: mediadownloadbot
    restart: always
    environment:
      - TOKEN
      - LOGGING_LEVEL
      - COBALT_URL
    mem_limit: 400m
    depends_on:
      - cobalt

  cobalt:
    image: ghcr.io/imputnet/cobalt:11
    init: true
    read_only: true
    restart: unless-stopped
    container_name: cobalt
    ports:
      - 9000:9000/tcp
    environment:
      API_URL: $API_URL
      FORCE_LOCAL_PROCESSING: always
    labels:
      - com.centurylinklabs.watchtower.scope=cobalt

  watchtower:
    image: ghcr.io/containrrr/watchtower
    restart: unless-stopped
    command: --cleanup --scope cobalt --interval 900 --include-restarting
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
