services:
  bot:
    build: .
    image: mediadownbot:latest
    container_name: tgbot-downloader
    restart: always
    environment:
      - TOKEN
      - LOGGING_LEVEL
      - TIKTOK_TOKEN
      - INSTAGRAM_TOKEN
