---

- name: Install bot
  hosts: hosts
  tasks:
    - name: Create working directory
      ansible.builtin.file:
        path: mediabot
        state: directory

    - name: Copy image
      ansible.builtin.copy:
        src: image.tar
        dest: mediabot

    - name: Copy compose
      ansible.builtin.copy:
        src: docker-compose.yml
        dest: mediabot

    - name: Copy .env
      ansible.builtin.copy:
        src: .env
        dest: mediabot

    - name: Load image
      community.docker.docker_image_load:
        path: mediabot/image.tar
      register: result

    - name: Run bot
      community.docker.docker_compose:
        project_src: mediabot
