name: Deploy bot

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [ "created" ]

jobs:

  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker build
      run: |
        docker build -t mediadownbot:latest .
        docker save mediadownbot:latest -o image.tar
    - name: Upload image to artifacts
      uses: actions/upload-artifact@v3
      with:
        name: image
        path: image.tar

  deploy:
    needs: build
    name: Deploy bot
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'created'
    steps:
    - uses: actions/checkout@v3
    - name: Download image
      uses: actions/download-artifact@v3
      with:
        name: image
    - name: Create .env file
      run: |
        echo "TOKEN=${{ secrets.TG_TOKEN }}" > .env
        echo "RAPIDAPI_TOKEN=${{ secrets.RAPIDAPI_TOKEN }}" >> .env
    - name: Deploy
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: playbook.yml
        key: ${{ secrets.HOST_SSH_KEY }}
        inventory: |
          [hosts]
          bot_host ansible_host=${{ secrets.SERVER_IP }} ansible_user=root ansible_port=9999
